openapi: 3.0.0
info:
  title: Vendad de Celulares
  description: Api desenvolvida para avaliar conhecimentos de programação no framework Laravel.
  version: 1.0.0
paths:
  /products:
    get:
      summary: Obter dados
      responses:
        '200':
          description: Sucesso
  /sales:
    get:
      summary: Obter dados
      responses:
        '200':
          description: Sucesso