# Use a imagem oficial do MySQL 8.0
FROM mysql:8.0.29

# Defina variáveis de ambiente para a senha do root (altere conforme necessário)
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=adorei
ENV MYSQL_USER=adorei
ENV MYSQL_PASSWORD=1234

# Copie o arquivo de configuração personalizado, se necessário
# COPY my.cnf /etc/mysql/my.cnf

# Exponha a porta padrão do MySQL
EXPOSE 3306
